spartakiada/zawody/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from spartakiada import views
from loging import views as loging


urlpatterns = [
    # url(r'^admin/', admin.urls),
    url(r'^$', views.MenuView.as_view(),
        name='menu'),
    url(r'^about/', views.AboutView.as_view(),
        name='about'),
    url(r'^players/', views.PlayersView.as_view(),
        name='players'),
    url(r'^add_player/', views.PlayerAddView.as_view(),
        name='add-player'),
    url(r'^delete_player/', views.PlayerDeleteView.as_view(),
        name='delete-player'),
    url(r'^teams/', views.TeamsView.as_view(),
        name='teams'),
    url(r'^player_details/(?P<id>(\d)+)/$', views.PlayerDetailsView.as_view(),
        name='player'),
    url(r'^stats/$', views.Stats.as_view(),
        name='stats'),
    url(r'refresh_stats/$', views.refresh_stats,
        name='refresh-stats'),
    url(r'^add_team/', views.TeamAddView.as_view(),
        name='add-team'),
    url(r'^delete_teams/', views.TeamsDeleteView.as_view(),
        name='delete-teams'),
    url(r'^team_details/(?P<team_id>(\d)+)', views.TeamDetailsView.as_view(),
        name='team-details'),
    url(r'^team_add_members/(?P<team_id>(\d)+)', views.TeamAddMembersView.as_view(),
        name='team-add-members'),
    url(r'^team_remove_members/(?P<team_id>(\d)+)', views.TeamRemoveMembersView.as_view(),
        name='team-remove-members'),
    url(r'^games/', views.GamesView.as_view(),
        name='games'),
    url(r'^add_game/', views.GameAddView.as_view(),
        name='add-game'),
    url(r'^delete_games/', views.GamesDeleteView.as_view(),
        name='delete-games'),
    url(r'^add_cup/', views.CupAddView.as_view(),
        name='add-cup'),
    url(r'^cup_add_games/(?P<cup_id>(\d)+)', views.CupAddGamesView.as_view(),
        name='cup-add-games'),
    url(r'^knockout/(?P<tournament_id>(\d)+)/(?P<lap>(\d)+)/$', views.KnockoutView.as_view(),
        name='knockout'),
    url(r'^next_round/(?P<tournament_id>(\d)+)/(?P<lap>(\d)+)/$', views.knockout_next_round),
    url(r'^cup/(?P<cup_id>(\d)+)', views.CupView.as_view(),
        name='cup'),
    url(r'^cups_list/$', views.CupsListView.as_view(),
        name='cups'),
    url(r'^participations_add_to_game/(?P<tournament_id>(\d)+)', views.ParticipationsAddToGameView.as_view(),
        name='participations'),
    url(r'^team_add_to_game/(?P<tournament_id>(\d)+)', views.TeamsAddToGameView.as_view(),
        name='team-add-game'),
    url(r'^team_stats/(?P<team_id>(\d)+)', views.TeamDetailsStatsView.as_view(),
        name='team-stats'),
    url(r'^delete_cup/(?P<cup_id>(\d)+)', views.CupDeleteView.as_view(),
        name="cup-delete"),

    url(r'^register/$', loging.UserCreateView.as_view(),
        name='register'),
    url(r'^login/$', loging.UserLoginView.as_view(),
        name='login'),
    url(r'^logout/$', loging.UserLogoutView.as_view(),
        name='logout')
]

spartakiada/spartakiada/models.py
from django.db import models
from django.urls import reverse


class Player(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return '%s' % self.name

    def get_absolute_url(self):
        return reverse('players')


    """
    Not perfect way to get players gender basing on their first name.
    Works only for polish names.
    """
    @property
    def gender(self):
        male_names = ["Bonawentura", "Kuba", "Kosma", "Attyla", "Barnaba", "Seba", "Dyzma", "Zawisza"]
        female_names = ["Miriam", "Nicole", "Noemi", "Beatrycze", "Nel"]
        name = self.name.partition(' ')[0]
        if name.endswith("a") and name not in male_names or name in female_names:
            return "F"
        else:
            return "M"



class Team(models.Model):
    name = models.CharField(max_length=128, unique=True)
    mates = models.ManyToManyField(Player, through='Member')

    def __str__(self):
        return '%s' % self.name


# enables players to be team members
class Member(models.Model):
    player = models.ForeignKey(Player)
    team = models.ForeignKey(Team)

    def __str__(self):
        return '%s' % self.player.name


# allow us to use the same functions for players and teams
class Partaker(models.Model):
    player = models.ForeignKey(Player, null=True)
    team = models.ForeignKey(Team, null=True)

    def __str__(self):
        if self.player:
            return self.player.name
        elif self.team:
            return self.team.name
        else:
            return "unknown partaker"

    @property
    # returns list of dictionaries made of duel-like objects
    def details(self):
        random_player = Player.objects.get(name="Random")
        random = Partaker.objects.get(player=random_player)
        participations = Participation.objects.filter(partaker=self)
        player_info = []
        if participations.count() != 0 and self != random:
            duels = []
            win = []
            for participation in participations:
                duels.append(Duel.objects.filter(player1=participation))
                duels.append(Duel.objects.filter(player2=participation))
            flat_duels = [item for sublist in duels for item in sublist]
            for duel in flat_duels:
                if duel.player1.partaker != random \
                        and duel.player2.partaker != random \
                        and duel.player1 != duel.player2:
                    player_info.append({
                        'player1': duel.player1.partaker,
                        'player2': duel.player2.partaker,
                        'points1': duel.points1,
                        'points2': duel.points2,
                        'game_name': duel.tournament.game.name,
                        'tournament_name': duel.tournament.cup.name,
                        'tournament_date': duel.tournament.cup.date,
                        'lap': duel.lap,
                    })
                elif duel.player1 == duel.player2:
                    win.append({
                        'player1': duel.player1.partaker,
                        'player2': duel.player2.partaker,
                        'points1': duel.points1,
                        'points2': duel.points2,
                        'game_name': duel.tournament.game.name,
                        'tournament_name': duel.tournament.cup.name,
                        'tournament_date': duel.tournament.cup.date,
                        'lap': duel.lap,
                    })
            # won objects are doubled, so we delete every second
            if len(win) > 0:
                del win[::2]

            # join both dictionaries
            player_info += win

        player_info = sorted(player_info, key=lambda k: k['tournament_date'], reverse=True)
        return player_info

    @property
    # returns dictionary
    def duels(self):
        player_info = self.details
        games_won = 0
        games_played = 0
        for duel in player_info:
            if duel['points1'] is not None:
                if duel['player1'] == self and duel['points1'] > duel['points2']:
                    games_won += 1
                    games_played += 1
                elif duel['player2'] == self and duel['points1'] < duel['points2']:
                    games_won += 1
                    games_played += 1
                else:
                    games_played += 1
        return {"won": games_won,
                "played": games_played}

    @property
    # returns list of duel objects
    def tournaments_won(self):
        player_info = self.details
        won_tournaments = []
        for duel in player_info:
            if duel['player1'] == duel['player2']:
                won_tournaments.append(duel)
        return won_tournaments

    @property
    # returns integer
    def was_second(self):
        silver_winners = []
        tournaments_participated = Tournament.objects.filter(participants=self)
        for tournaments in tournaments_participated:
            if tournaments.second is not None:
                silver_winners.append(tournaments.second.partaker)
        return silver_winners.count(self)

    @property
    # returns integer
    def tournaments_participated(self):
        participations = Participation.objects.filter(partaker=self)
        parts = []
        for part in participations:
            parts.append(part.tournament.cup.id)
        return len(set(parts))


# type of game/sport
class Game(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return '%s' % self.name


class Cup(models.Model):
    name = models.CharField(max_length=128)
    date = models.DateField()

    class Meta:
        unique_together = ("name", "date")

    def __str__(self):
        return '%s' % self.name

    def get_absolute_url(self):
        return reverse('cup-add-games', kwargs={'cup_id': self.id})


class Tournament(models.Model):
    participants = models.ManyToManyField('Partaker', through='Participation')
    game = models.ForeignKey(Game, null=True)
    cup = models.ForeignKey(Cup, null=True)
    individual = models.BooleanField(default=True)

    class Meta:
        unique_together = ("cup", "game", "individual")

    @property
    # returns boolean value
    def is_over(self):
        duels = Duel.objects.filter(tournament=self).order_by("-lap")
        if duels[0].player1 is None:
            return False
        else:
            return True

    @property
    # returns duel object
    def winner(self):
        if self.is_over:
            duels = Duel.objects.filter(tournament=self).order_by("-lap")
            return duels[0]

    @property
    # returns participations object
    def second(self):
        if self.is_over:
            duels = Duel.objects.filter(tournament=self).order_by("-lap")
            if duels[0].player1 == duels[0].player2:
                if duels[1].player1 != duels[0].player1:
                    return duels[1].player1
                else:
                    return duels[1].player2

    @property
    # returns integer
    def last_lap(self):
        last_lap = Duel.objects.filter(tournament=self).last().lap
        return last_lap


class Participation(models.Model):
    partaker = models.ForeignKey(Partaker, null=True)
    tournament = models.ForeignKey(Tournament)


# atomic event of all games, which is a single duel of two players
class Duel(models.Model):
    tournament = models.ForeignKey(Tournament)
    player1 = models.ForeignKey(Participation, related_name='game_played')
    player2 = models.ForeignKey(Participation, related_name='game_played2')
    points1 = models.IntegerField(null=True)
    points2 = models.IntegerField(null=True)
    lap = models.IntegerField(null=True)


# model used for stats
class PlayerCache(models.Model):
    partaker = models.ForeignKey(Partaker, default=None)
    won = models.IntegerField(null=True)
    played = models.IntegerField(null=True)
    tournament_won = models.IntegerField(null=True)
    tournament_second = models.IntegerField(null=True)
    tournament_participated = models.IntegerField(null=True)

spartakiada/spartakiada/forms.py
from django import forms
from .models import Player, Team, Game, Cup


class PlayerAddForm(forms.ModelForm):
    class Meta:
        model = Player
        fields = [
            'name'
        ]


class PlayerDeleteForm(forms.ModelForm):
    players = forms.ModelMultipleChoiceField(
        Player.objects.all(), widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = Player
        fields = [
            'name'
        ]


class TeamAddForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = [
            'name', 'mates'
        ]


class TeamsDeleteForm(forms.ModelForm):
    teams = forms.ModelMultipleChoiceField(
        Team.objects.all(), widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = Team
        fields = [
            'name'
        ]


class GameAddForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = [
            'name'
        ]


class GamesDeleteForm(forms.ModelForm):
    games = forms.ModelMultipleChoiceField(
        Game.objects.all(), widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = Game
        fields = [
            'name'
        ]


class CupAddForm(forms.ModelForm):

    class Meta:
        model = Cup
        fields = [
            'name', 'date'
        ]

spartakiada/spartakiada/templates/spartakiada/about_view.html
{% extends 'spartakiada/base.html' %}
{% load static %}
{% block content %}
    <h3 class="headtext">Kilka słów o nas ...</h3>
        <div style="height: 50px;"></div>

        <div style="display: inline-block; margin-right: 30px;">
        <img style="margin-bottom: 10px;" src="{% static 'spartakiada/KR.jpg' %}" class="img-circle" alt="Kamil Radomski" width="146" height="146">
        <div>
            <p style="display: inline-block"><a class="maintext" href="https://www.linkedin.com/in/kamilmarekradomski/" target="_blank">
                <img width="40" style="margin-left: 30px;" src="{% static 'spartakiada/lin.gif' %}" /></a></p>&nbsp;
            <p style="display: inline-block"><a class="maintext" href="https://github.com/natancamenzind" target="_blank">
                <img width="40" style="margin-right: 30px;" src="{% static 'spartakiada/gh.gif' %}" /></a></p>
        </div>
        </div>

        <div style="display: inline-block;">
        <h3 class="maintext" style="margin-top: 0px;">Kamil Radomski</h3>
        <p><strong>Junior Backend Developer - Python</strong></p>
        <p>Wcześniej dziennikarz w Programie Drugim Polskiego Radia</p>
        <p>Za dziesięć lat prawdopodobnie będzie prowadził komunę <br>
            pod Pułtuskiem i pracował zdalnie</p>
        <p><a class="maintext">kamilmarekradomski@gmail.com</a></p>

        </div><br><br><br><br>

        <div style="display: inline-block; margin-right: 30px;">
        <img style="margin-bottom: 10px;" src="{% static 'spartakiada/TI.jpg' %}" class="img-circle" alt="Tomasz Iwanowski" width="146" height="146">
        <div>
            <p style="display: inline-block"><a class="maintext" href="https://www.linkedin.com/in/tomasz-iwanowski/" target="_blank">
                <img width="40" style="margin-left: 30px;" src="{% static 'spartakiada/lin.gif' %}" /></a></p>&nbsp;
            <p style="display: inline-block"><a class="maintext" href="https://github.com/tiwanowski96" target="_blank">
                <img width="40" style="margin-right: 30px;" src="{% static 'spartakiada/gh.gif' %}" /></a></p>
        </div>
        </div>

        <div style="display: inline-block;">
        <h3 class="maintext" style="margin-top: 0px;">Tomasz Iwanowski</h3>
        <p><strong>Junior Backend Developer - Python</strong></p>
        <p>Fanatyk lotnictwa, szybkich kobiet i pięknych samochodów</p>
        <p>Dlaczego postanowił się przebranżowić ?<br>"Płatne zabójstwa za bardzo brudzą sumienie"</p>
        <p><a class="maintext">tiwanowski96@gmail.com</a></p>

        </div><br><br><br><br>

        <div style="margin-left: 50px;">
        <h4 style="" class="maintext">Damian Więch</h4>
        <p>Graphic Designer</p>
        <p><a class="maintext">wiech.damian@gmail.com</a></p>
        </div>

{% endblock %}

spartakiada/spartakiada/templates/spartakiada/cup_form.html
{% extends 'spartakiada/base.html' %}

{% block content %}
    <h3 class="headtext">Dodaj turniej</h3>
    <form action="" method="POST">{% csrf_token %}
        <h3 class="maintext">Nazwa: </h3>
        {{ form.name }}
        <h3 class="maintext">Data (rrrr-mm-dd): </h3>
        {{ form.date }}
        <br>{{ form.errors }}<br>
        <input class="toggle" type="submit" value="&nbsp;DODAJ&nbsp;">
    </form>
{% endblock %}

spartakiada/spartakiada/templates/spartakiada/cup_list.html
{% extends 'spartakiada/base.html' %}

{% block content %}

<h3 class="headtext">Turnieje</h3>
<ol>
{% for cup in object_list %}
    <li><a class="maintext" href="/cup/{{cup.id}}/"><strong>{{ cup.name }}</strong> &nbsp;{{ cup.date }}</a></li>
{% empty %}
    <p class="maintext">BRAK TURNIEJÓW</p>
{% endfor %}
</ol>

{% endblock %}

spartakiada/spartakiada/templates/spartakiada/except_cup_ended.html
{% extends 'spartakiada/base.html' %}

{% block content %}

    <br>
        <h1 class="headtext" style="text-align: center">ROZGRYWKI W TEJ DYSCYPLINIE ZOSTAŁY JUŻ ZAKOŃCZONE</h1><br>
        <div style="margin: 0 auto; text-align: center">
            <button class="toggle" onclick="goBack()">&nbsp;COFNIJ&nbsp;</button>
        </div>

<script>
function goBack() {
    window.history.back();
}
</script>
{% endblock %}

spartakiada/spartakiada/templates/spartakiada/except_empty.html
{% extends 'spartakiada/base.html' %}

{% block content %}

    <br>
        <h1 class="headtext" style="text-align: center">NIE WYBRANO DYSCYPLIN DO TURNIEJU ! COFNIJ ABY DODAĆ</h1><br>
        <div style="margin: 0 auto; text-align: center">
            <button class="toggle" onclick="goBack()">&nbsp;COFNIJ&nbsp;</button>
        </div>

<script>
function goBack() {
    window.history.back();
}
</script>
{% endblock %}

spartakiada/spartakiada/templates/spartakiada/except_empty_input.html
{% extends 'spartakiada/base.html' %}

{% block content %}

    <br>
        <h1 class="headtext" style="text-align: center">PROSZĘ UZUPEŁNIĆ WSZYSTKIE WYNIKI ETAPU</h1><br>
        <div style="margin: 0 auto; text-align: center">
            <button class="toggle" onclick="goBack()">&nbsp;COFNIJ&nbsp;</button>
        </div>

<script>
function goBack() {
    window.history.back();
}
</script>
{% endblock %}

spartakiada/spartakiada/templates/spartakiada/games_delete_view.html
{% extends 'spartakiada/base.html' %}

{% block content %}

    <h3 class="headtext">Dyscypliny do usunięcia: </h3>
<form action="" method="POST">{% csrf_token %}
    <ol>
    {% for game in game_list %}
        <li><a class="maintext">{{game}} <input class="checkbox" type="checkbox"
            name="game" value="{{game}}"></a></li>
    {% endfor %}
    </ol>
    <input class="toggle" type="submit" value="&nbsp;USUŃ&nbsp;">
</form>


{% endblock %}

spartakiada/spartakiada/templates/spartakiada/knockout.html
{% extends 'spartakiada/base.html' %}

{% block content %}


<link rel="stylesheet" href="/static/spartakiada/style.css">


    <h1 class="headtext" style="text-align: center; font-size: 2.5em; "><a class="maintext" href="/cup/{{ tournament.cup.id }}/">{{ tournament.cup.name }}</a></h1><hr>
    <br><br>
<form action='#' method='POST'>
    {% csrf_token %}

    <h2 class="headtext">Dyscyplina <a class="maintext">{{tournament.game.name}}</a></h2><br>
        <div class="container"></div>

    {% for stage in stages %}
        {% if stage.player1.partaker == stage.player2.partaker %}
            <table class='{{stage.lap}}' id='win_bordered'>
                <tr>
                    <td class='nice {{stage.player1.partaker}}'><b>&nbsp;
                        {{stage.player1.partaker}}</b></td>
                </tr>
            <table>
        {% elif stage.lap|add:"0" == lap|add:"0" %}
            <table class="{{stage.lap}}" id="fight_bordered">

                <tr>
                    <td class="nice {{stage.player1.partaker}}">
                        &nbsp;{{stage.player1.partaker}}</td>
                    <td class="points"><input class="inputKO" type="number" name="{{stage.player1.partaker}}" value="{{stage.points1}}"></td>
                </tr>
                <tr>
                    <td class="nice {{stage.player2.partaker}}">
                        &nbsp;{{stage.player2.partaker}}</td>
                    <td class="points"><input class="inputKO" type="number" name="{{stage.player2.partaker}}" value="{{stage.points2}}"></td>
                </tr>

            </table>
        {% elif stage.lap|add:"0" != lap|add:"0" %}
            <table class="{{stage.lap}}">
                <tr>
                    <td class="nice {{stage.player1.partaker}}">&nbsp;
                        {{stage.player1.partaker}}</td>
                    <td class="points">{{stage.points1}}</td>
                </tr>
                <tr>
                    <td class="nice {{stage.player2.partaker}}">&nbsp;
                        {{stage.player2.partaker}}</td>
                    <td class="points">{{stage.points2}}</td>
                </tr>
            </table>
        {% else %}
        <p>Coś poszło nie tak</p>

        {% endif %}
    {% endfor %}
        <br><input class="toggle" type='submit' value='ZATWIERDŹ PUNKTY'>

</form>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript" src="/static/js/app.js"></script>
{% endblock %}

spartakiada/spartakiada/templates/spartakiada/menu.html
{% extends 'spartakiada/base.html' %}

{% block content %}
<div class="row" style="margin-left: 0px; margin-right: 0px; margin-top: 110px; height: 100%">
    <div class="col-sm-1"></div>
    <div class="col-sm-7">
        <h1 class="headtext" style="font-size: 3em;">

            Olimpijskie rozgrywki w zasięgu ręki

        </h1><br>
        <h2 class="maintext">

            Piłkarzyki w pracy? Counter Strike po godzinach? Koszykówka na osiedlu?

        </h2>
        <h3>
            <br><br>
            <p>Nie ważne w co grasz. Tutaj możesz szybciej i prościej zorganizować turniej w co tylko chcesz.</p><br>
            <p>Dodaj znajomych i wybierz dziedzinę. My zajmiemy się przygotowaniem losowej drabinki pucharowej,
                przechowaniem historii i prezentacją statystyk.</p><br>
            <p>Jest was za mało, żeby każdy mógł zagrać? Losowo przydzielmy niektórym przeciwnika, z&nbsp;którym nie
                sposób przegrać.</p><br>
            <p>Chcesz móc grać raz w zespołach, raz indywidualnie? Nie ma problemu! Wszystkie
                możliwości są dostępne tak dla zawodników indywidualnych, jak i dla drużyn.</p><br>
            <p>Wszystko za darmo, bez spamu i reklam!</p><br>

        </h3>

    </div>
    <div class="col-sm-2"></div>
    <div class="col-sm-2" style="height: 100vh; border-left: 2px solid #080808;">

        <br>
        <div class="affix">
        <ol><h3 class="headtext" style="font-size: 16px;">Ostatnie turnieje:</h3>
            <li style="font-size: 15px;"><a href="/cup/{{ cup.0.id }}" class="maintext" style="font-size: 15px;">{{ cup.0 }}</a></li>
            <li style="font-size: 15px;"><a href="/cup/{{ cup.1.id }}" class="maintext" style="font-size: 15px;">{{ cup.1 }}</a></li>
            <li style="font-size: 15px;"><a href="/cup/{{ cup.2.id }}" class="maintext" style="font-size: 15px;">{{ cup.2 }}</a></li>
        </ol>
        <ol><h3 class="headtext" style="font-size: 16px;">Najlepsi zawodnicy:</h3>
            <li style="font-size: 15px;"><a href="/player_details/{{ players.0.partaker.player.id }}" class="maintext" style="font-size: 15px;">{{ players.0.partaker }}</a></li>
            <li style="font-size: 15px;"><a href="/player_details/{{ players.1.partaker.player.id }}" class="maintext" style="font-size: 15px;">{{ players.1.partaker }}</a></li>
            <li style="font-size: 15px;"><a href="/player_details/{{ players.2.partaker.player.id }}" class="maintext" style="font-size: 15px;">{{ players.2.partaker }}</a></li>

        </ol>
        <ol><h3 class="headtext" style="font-size: 16px;">Najlepsze zespoły:</h3>
            <li style="font-size: 15px;"><a href="/team_details/{{ teams.0.partaker.team.id }}" class="maintext" style="font-size: 15px;">{{ teams.0.partaker }}</a></li>
            <li style="font-size: 15px;"><a href="/team_details/{{ teams.1.partaker.team.id }}" class="maintext" style="font-size: 15px;">{{ teams.1.partaker }}</a></li>
            <li style="font-size: 15px;"><a href="/team_details/{{ teams.2.partaker.team.id }}" class="maintext" style="font-size: 15px;">{{ teams.2.partaker }}</a></li>
        </ol>
        </div>

    </div>
</div>
{% endblock %}

spartakiada/spartakiada/templates/spartakiada/player_details_view.html
{% extends 'spartakiada/base.html' %}

{% block content %}

<h3 class="headtext">{{player.name}}</h3>
<br>
    <div>
        <h4 class="maintext">
        {% if player.gender == "F" %}

            Zawodniczka wygrała

        {% else %}

            Zawodnik wygrał

        {% endif %}

        {{partaker.duels.won}} na {{partaker.duels.played}} spotkań.
        </h4>

    </div><br>

    <div>
        <h4 class="maintext" style="color: black">
        {% for won in partaker.tournaments_won %}

                {% if player.gender == "F" %}

                    Zwyciężczyni

                {% else %}

                    Zwycięzca

                {% endif %}

            turnieju {{won.tournament_name}} ({{won.tournament_date}}) w <b>{{won.game_name}}</b>.

            Po {{won.lap|add:"-1"}} rundach.<br><br>
            {% endfor %}
        <br></h4>



    </div>

    {% include 'spartakiada/detail_view.html' %}

{% endblock %}

spartakiada/spartakiada/templates/spartakiada/player_view.html
{% extends 'spartakiada/base.html' %}

{% block content %}

    {% include 'spartakiada/player_list_itself.html' %}
    <a href="{% url 'add-player' %}"
       class="toggle">
        &nbsp;DODAJ ZAWODNIKA&nbsp;</a>&nbsp;
    <a class="toggle" href="{% url 'delete-player' %}">
        &nbsp;USUŃ ZAWODNIKÓW&nbsp;</a>

{% endblock %}

spartakiada/spartakiada/templates/spartakiada/stats_players.html
{% block content %}

<br>
<div class="tabcon">
    <h3 class="headtext">Zawodnicy</h3>
    <table class="stats" style="font-size: 16px;">
        <thead>
            <tr style="background-color: #DAA520;">
                <th>Imię i nazwisko</th>
                <th>Liczba zwycięstw</th>
                <th>Stoczone rozgrywki</th>
                <th>Wygrane turnieje</th>
                <th>Drugie miejsce</th>
                <th>Udziały w turniejach</th>
            </tr>
        </thead>
        <tbody>

        {% for player in cache %}
        {% if player.partaker.player %}

            <tr>
                <td>{{player.partaker}}</td>
                <td>{{player.won}}</td>
                <td>{{player.played}}</td>
                <td>{{player.tournament_won}}</td>
                <td>{{player.tournament_second}}</td>
                <td>{{player.tournament_participated}}</td>
            </tr>

        {% endif %}

        {% endfor %}
        </tbody>
    </table>
    <style>
            table, th, td {
            border: 1px solid black;
            }
    </style>
</div>

{% endblock %}

spartakiada/spartakiada/templates/spartakiada/stats_teams.html
{% block content %}
<br>
<div class="tabcon">
    <h3 class="headtext">Drużyny</h3>
    <table class="stats" style="font-size: 16px;">
        <thead>
            <tr style="background-color: #DAA520;">
                <th>Nazwa</th>
                <th>Liczba zwycięstw</th>
                <th>Stoczone rozgrywki</th>
                <th>Wygrane turnieje</th>
                <th>Drugie miejsce</th>
                <th>Udziały w turniejach</th>
            </tr>
        </thead>
        <tbody>

        {% for player in cache %}
        {% if player.partaker.team %}

            <tr>
                <td>{{player.partaker}}</td>
                <td>{{player.won}}</td>
                <td>{{player.played}}</td>
                <td>{{player.tournament_won}}</td>
                <td>{{player.tournament_second}}</td>
                <td>{{player.tournament_participated}}</td>
            </tr>

        {% endif %}

        {% endfor %}
        </tbody>
    </table>
<style>
            table, th, td {
            border: 1px solid black;
            }
    </style>
</div>

{% endblock %}

spartakiada/spartakiada/templates/spartakiada/team_detail_view.html
{% extends 'spartakiada/base.html' %}

{% block content %}

    <h3 class="headtext">{{ team }}</h3>

    <ol>
    {% for member in team_members %}
        <li>
            <a class="maintext" href="/player_details/{{ member.player.id }}">{{ member }}</a>
        </li>
        {% empty %}
        <a class="maintext">BRAK ZAWODNIKÓW</a>
    {% endfor %}
    </ol><br>
    <a class="toggle" href="/team_add_members/{{ team.id }}"
       >
        &nbsp;DODAJ ZAWODNIKÓW&nbsp;</a>
    <a class="toggle" href="/team_remove_members/{{ team.id }}"
       >
        &nbsp;USUŃ ZAWODNIKÓW&nbsp;</a>
    <br><br>
    <a class="toggle" href="/team_stats/{{ team.id }}"
       >
        &nbsp;STATYSTYKA&nbsp;</a>

{% endblock %}
style="text-decoration: none;"